# Generated by Django 4.1.7 on 2023-03-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book", index=models.Index(fields=["id"], name="id_index"),
        ),
    ]
